RECOVERY_VARIANT := twrp
RECOVERY_SDCARD_ON_DATA := true
TW_INCLUDE_FUSE_NTFS := true
TARGET_RECOVERY_DEVICE_DIRS += device/sharp/ss2/twrp
BOARD_KERNEL_CMDLINE += selinux=0
BOARD_KERNEL_CMDLINE += enforcing=0

TARGET_HW_DISK_ENCRYPTION := true
TARGET_CRYPTFS_HW_PATH := vendor/qcom/opensource/cryptfs_hw
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TW_USE_TOOLBOX := true
TARGET_COPY_OUT_VENDOR := vendor
TARGET_KEYMASTER_WAIT_FOR_QSEE := true
TARGET_RECOVERY_QCOM_RTC_FIX := true
BOARD_HAS_REMOVABLE_STORAGE := true
# Encryption support
TW_INCLUDE_CRYPTO := true
TARGET_HW_DISK_ENCRYPTION := true
TW_INCLUDE_FBE := true

TWRP_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true
RECOVERY_VARIANT := twrp

#File System
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_PERSISTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_BUILD_SYSTEM_ROOT_IMAGE := true
BOARD_USES_RECOVERY_AS_BOOT := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_USES_MKE2FS := true
# GPT Utils
BOARD_PROVIDES_GPTUTILS := true

# Recovery
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

AB_OTA_UPDATER := true

# Crypto
TW_INCLUDE_CRYPTO := true
TARGET_HW_DISK_ENCRYPTION := true
#TARGET_KEYMASTER_WAIT_FOR_QSEE := true
PLATFORM_SECURITY_PATCH := 2025-12-31

# TWRP
TW_THEME := portrait_hdpi
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
TW_EXCLUDE_SUPERSU := true
TARGET_RECOVERY_QCOM_RTC_FIX := true
BOARD_SUPPRESS_SECURE_ERASE := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_INCLUDE_NTFS_3G := true
TW_DEFAULT_BRIGHTNESS := 80
TW_SCREEN_BLANK_ON_BOOT := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_EXTRA_LANGUAGES := true
TARGET_RECOVERY_DEVICE_MODULES += android.hardware.boot@1.0
#TW_RECOVERY_ADDITIONAL_RELINK_FILES := ${OUT_DIR}/target/product/ss2/system/lib64/android.hardware.boot@1.0.so


TW_INCLUDE_REPACKTOOLS := true


# Debug flags
TWRP_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true


 


